spring:
  application:
    name: java-test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    # hikari:
      # auto-commit: false

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: create-drop
    # open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: debug

nplus1detector:
  enabled: true
  threshold: 2
  exclude:
  # - select b1_0.author_id,b1_0.id,b1_0.title from book b1_0 where b1_0.author_id=?
  # - select o1_0.id,o1_0.order_number from "order" o1_0 where o1_0.id=?
  level: warn
