### 클래스 단위의 @Transactional 상황에서 감지하는 것을 검증
GET http://localhost:8080/api/library/v1/authors

### 메서드 단위의 @Transactional 상황에서 감지하는 것을 검증
GET http://localhost:8080/api/library/v2/authors

### OSIV를 이용한 지연 조회 상황에서 감지하는 것을 검증
GET http://localhost:8080/api/library/v3/authors
