spring:
  application:
    name: kotlin-test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: create-drop

logging:
  level:
    org:
      hibernate:
        SQL: debug

nplus1detector:
  enabled: true
