name: 'pre-release-validation'

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions: write-all

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key-java: ${{ steps.cache-java.outputs.key }}
      cache-key-kotlin: ${{ steps.cache-kotlin.outputs.key }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate cache key for java-test
        id: cache-java
        run: echo "key=validation-${{ runner.os }}-gradle-java-${{ hashFiles('java-test/**/*.gradle*', 'java-test/**/gradle-wrapper.properties') }}" >> $GITHUB_OUTPUT

      - name: Generate cache key for kotlin-test
        id: cache-kotlin
        run: echo "key=validation-${{ runner.os }}-gradle-kotlin-${{ hashFiles('kotlin-test/**/*.gradle*', 'kotlin-test/**/gradle-wrapper.properties') }}" >> $GITHUB_OUTPUT

  validation:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - module: java-test
            cache-key: cache-key-java
          - module: kotlin-test
            cache-key: cache-key-kotlin
    steps:
      - uses: actions/checkout@v4

      - name: Cache Gradle packages
        id: cache-gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ needs.setup.outputs[matrix.cache-key] }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run test in ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:test

      - name: Upload HTML report for ${{ matrix.module }}
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.module }}-report
          path: ${{ github.workspace }}/${{ matrix.module }}/build/reports/tests/test/

      - name: Publish validation results for ${{ matrix.module }}
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: ${{ github.workspace }}/${{ matrix.module }}/build/test-results/test/TEST-*.xml

      - name: Comment test results on PR for ${{ matrix.module }}
        uses: mikepenz/action-junit-report@v4
        if: github.event_name == 'pull_request' && always()
        with:
          report_paths: ${{ github.workspace }}/${{ matrix.module }}/build/test-results/test/TEST-*.xml
