name: 'pre-release-tagging'

on:
  push:
    branches:
      - main
      
permissions: write-all
  
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create a tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "2.2.0"
